package com.redundo.obddiscover

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/**
 * Who is this car, and where does its maker keep its enhanced data.
 *
 * ENTIRELY OFFLINE. Both tables are bundled (~24 KB): a WMI->make map from NHTSA vPIC and a
 * per-make (header, service, block) hint table derived from OBDb. A car park is exactly
 * where a network lookup fails, and the whole point of these hints is to work there.
 *
 * See assets/ATTRIBUTION.txt. The OBDb-derived table is CC-BY-SA-4.0 and stays that way.
 */
object VehicleId {

    private var wmiMap: JSONObject? = null
    private var hints: JSONObject? = null
    private var supported: JSONObject? = null

    /**
     * OBDb locations at MODEL granularity, keyed "Make|Model".
     *
     * ADDITIVE. The make-level tables are untouched and remain the fallback, because their
     * contents cannot be reproduced from today's OBDb signalsets -- the shipped BMW entry
     * holds 2,009 requests on 6F1 across 79 blocks where OBDb/BMW itself carries 46
     * commands. Whatever second source built that, overwriting it would lose it.
     *
     * What this file adds is separation. OBDb keeps one repo per model and one per make;
     * the make repo is an aggregate, so a Silverado was being handed Malibu, Camaro, Bolt
     * and Traverse locations -- 39 rows over ten headers, where its own model needs 18 over
     * four, and a Bolt is 11-bit while a Corvette is 29-bit.
     */
    private var models: JSONObject? = null
    private var contributed: JSONObject? = null
    private var stdPids: JSONObject? = null

    fun load(ctx: Context) {
        if (wmiMap != null) return
        runCatching {
            wmiMap = JSONObject(ctx.assets.open("wmi_to_make.json").bufferedReader().readText())
            hints = JSONObject(ctx.assets.open("obdb_hints.json").bufferedReader().readText())
            supported = JSONObject(ctx.assets.open("obdb_supported.json").bufferedReader().readText())
            models = JSONObject(ctx.assets.open("obdb_models.json").bufferedReader().readText())
        }
        // Generated by tools/merge_vehicles.py from the vehicles directory. Separate runCatching: a
        // clone built without the Gradle task must still start, just without contributions.
        runCatching {
            contributed = JSONObject(
                ctx.assets.open("vin_patterns.json").bufferedReader().readText())
        }
        runCatching {
            stdPids = JSONObject(
                ctx.assets.open("pid_standard.json").bufferedReader().readText())
        }
    }

    /** Models this make has model-specific data for. Empty when it has none. */
    fun modelsFor(make: String): List<String> {
        val m = models ?: return emptyList()
        val out = ArrayList<String>()
        for (k in m.keys()) if (k.substringBefore('|') == make) out.add(k.substringAfter('|'))
        return out.sorted()
    }

    /**
     * OBDb repository from a make plus whatever vPIC called the model or series.
     *
     * Replaces signature matching as the route to a model, because that route does not work.
     * It required every documented (header, block) pair to be found, and OBDb documents them
     * across modules this app deliberately never probes -- 753, 7A2, 7B0 on a Subaru. Four
     * captures on builds carrying it produced zero matches.
     *
     * The "122 of 147 uniquely identifiable" figure behind it was measured on FULL
     * signatures. On the headers the app actually sees it is 63 of 94, and the reachable
     * subset is usually one or two pairs, which discriminates nothing. That was a property
     * of the data, not of the app.
     *
     * vPIC gives the answer directly, and tries series when the model name is not a repo:
     * a 535i is not an OBDb repository but BMW-5-Series is.
     */
    fun repoForName(make: String, model: String, series: String): String {
        val m = models ?: return ""
        val want = listOf(model, series).filter { it.isNotBlank() }
            .map { "$make-${it.replace(" ", "-")}".lowercase() }
        for (k in m.keys()) {
            val r = m.optJSONObject(k)?.optString("r", "") ?: continue
            if (r.lowercase() in want) return r
        }
        return ""
    }

    /** OBDb repository for a model, e.g. "Chevrolet-Silverado-1500". "" if unknown. */
    fun repoFor(make: String, model: String): String =
        models?.optJSONObject("$make|$model")?.optString("r", "") ?: ""

    /** (header, block) pairs a model is documented to answer at -- its signature. */
    fun signatureOf(make: String, model: String): Set<Pair<String, String>> {
        val arr = models?.optJSONObject("$make|$model")?.optJSONArray("h") ?: return emptySet()
        val out = HashSet<Pair<String, String>>()
        for (i in 0 until arr.length()) {
            val r = arr.optJSONArray(i) ?: continue
            out.add(r.optString(0).uppercase() to r.optString(2).uppercase())
        }
        return out
    }

    /** Known requests for one model, same shape as supportedFor. */
    fun supportedForModel(make: String, model: String): List<Pair<String, String>> {
        // CASE-INSENSITIVE, because the two sides spell it differently and always will.
        // OBDb files the Ioniq 5 as "Hyundai|IONIQ 5"; our own record, written by a person,
        // says "Ioniq 5". An exact match returned nothing for the one car that most needed
        // the model-level list -- 34 requests aimed at the battery, charger, motor and
        // odometer, none of which the make-level list reaches as precisely.
        val models0 = models ?: return emptyList()
        val want = "$make|$model".lowercase()
        val key = models0.keys().asSequence().firstOrNull { it.lowercase() == want }
            ?: return emptyList()
        val arr = models0.optJSONObject(key)?.optJSONArray("k") ?: return emptyList()
        val out = ArrayList<Pair<String, String>>()
        for (i in 0 until arr.length()) {
            val row = arr.optString(i); val c = row.indexOf(':')
            if (c <= 0) continue
            val hdr = row.substring(0, c).uppercase(); val req = row.substring(c + 1).uppercase()
            // 29-bit targets are written as four characters ("DA11"); the bus address is
            // DA11F1. Filtering to three dropped every one, so on a 29-bit vehicle phase 0
            // matched nothing against liveHeaders: a Silverado offered 409 known requests
            // and sent 20, all of which were the identification DIDs.
            val h = when {
                hdr.length == 3 && hdr != "6F1" -> hdr
                hdr.length == 4 && hdr.startsWith("DA") -> hdr + "F1"
                else -> continue
            }
            if (!h.all { it in "0123456789ABCDEF" }) continue
            if (!req.startsWith("22") || req.length < 6) continue
            out.add(h to req)
        }
        return out.distinct()
    }

    /**
     * Which model this vehicle ANSWERS like, from what the scan actually found.
     *
     * Not decoded from the VIN. Alan's vin.cpp documents why that route is brittle --
     * positional rules are not stable across model years, year codes repeat every 30 years,
     * and a 2011-12 Express van once satisfied the GM 1500 diesel rule exactly. A previous
     * attempt at model naming in this app was abandoned for being wrong too often, and it
     * was decoding rather than measuring.
     *
     * This asks the car instead: 122 of 147 documented models (82%) have a unique set of
     * (header, block) pairs, so what answered is usually enough to say which model it is.
     *
     * Returns EVERY model whose signature is fully contained in what was found, so a tie is
     * reported as a tie rather than resolved by guessing. Bolt EV and Bolt EUV are the same
     * platform and will always tie; saying so is correct.
     */
    fun modelsMatching(make: String, found: Set<Pair<String, String>>): List<String> {
        if (found.isEmpty()) return emptyList()
        val scored = modelsFor(make).mapNotNull { model ->
            val sig = signatureOf(make, model)
            if (sig.isEmpty()) null else model to (sig intersect found).size to sig.size
        }
        // A model only qualifies if EVERY location it documents was seen. A partial match is
        // a different vehicle that happens to share a block.
        val full = scored.filter { it.first.second == it.second }.map { it.first.first to it.second }
        if (full.isEmpty()) return emptyList()
        val best = full.maxOf { it.second }
        return full.filter { it.second == best }.map { it.first }.sorted()
    }

    /**
     * Makes this VIN's WMI builds for, most likely first. Empty when the WMI is unknown.
     *
     * A WMI is a plant, not a brand, so one can legitimately carry several makes: 1N4 is
     * Nissan AND Infiniti, 3C4 is the whole Chrysler/Dodge/Jeep/Ram/Fiat family, and 19U
     * is Acura built by Honda. The table stores a bare string for the ordinary case and an
     * array for those, so only the 53 that need it pay for it.
     */
    fun makes(vin: String): List<String> {
        if (vin.length < 3) return emptyList()
        val v = wmiMap?.opt(vin.take(3).uppercase()) ?: return emptyList()
        if (v is JSONArray) return (0 until v.length()).map { v.optString(it) }.filter { it.isNotEmpty() }
        val s = v.toString()
        return if (s.isEmpty()) emptyList() else listOf(s)
    }

    /** Manufacturer from the WMI (VIN chars 1-3), or "" if unknown. */
    fun make(vin: String): String = makes(vin).firstOrNull() ?: ""

    /**
     * The other makes this VIN's plant builds for -- everything after the primary.
     *
     * Passed to the hint lookups as `also`, never merged into the make itself. Merging at
     * make level looked tempting and is wrong: one rebadge (the Chevrolet City Express is
     * a Nissan NV200) would drag Infiniti's locations into every Chevrolet scan, taking
     * Nissan's own hint set from 12 rows to 90. Scoped to the WMI, a 1N4 gets Nissan then
     * Infiniti and nothing else does.
     */
    fun siblings(vin: String): List<String> = makes(vin).drop(1)

    /**
     * Model year from VIN position 10.
     *
     * The code repeats on a 30-year cycle, so 'L' is 1990 AND 2020. Disambiguated by
     * position 7: for 1980-2009 it is numeric, for 2010+ it is alphabetic. That rule is
     * how the standard itself resolves the collision.
     */
    fun year(vin: String): Int? {
        if (vin.length < 10) return null
        val c = vin[9].uppercaseChar()
        val codes = "ABCDEFGHJKLMNPRSTVWXY123456789"
        val i = codes.indexOf(c)
        if (i < 0) return null
        val older = 1980 + i
        val newer = 2010 + i
        val pos7Alpha = vin.length >= 7 && vin[6].isLetter()
        return if (pos7Alpha) { if (newer <= 2039) newer else older } else older
    }

    /** What a VIN tells us with no network at all. */
    data class Info(val vin: String, val wmi: String, val make: String, val year: Int?) {
        val known: Boolean get() = make.isNotEmpty()
    }

    fun identify(vin: String) = Info(vin, vin.take(3).uppercase(), make(vin), year(vin))

    /** One documented location: header, service, 256-DID block, and whether it is powertrain. */
    data class Hint(val header: String, val service: String, val block: String,
                    val powertrain: Boolean)

    /**
     * Make and model for a VIN, from the vehicles directory -- cars people actually scanned.
     *
     * Matched on VIN positions 1-8, longest prefix first, so a contributor who only knew
     * the first five characters still resolves. This is the route vPIC cannot provide:
     * prefix enumeration against DecodeVINValuesBatch names a model for 31% of WMIs, and
     * DecodeWMI is silent for most imports -- JTM, WBA, KM8 and JF2 among them.
     */
    fun contributedId(vin: String): Pair<String, String>? {
        val c = contributed?.optJSONObject("patterns") ?: return null
        val v = vin.uppercase()
        for (n in minOf(8, v.length) downTo 3) {
            val a = c.optJSONArray(v.take(n)) ?: continue
            val make = a.optString(0); val model = a.optString(1)
            if (make.isNotEmpty()) return make to model
        }
        return null
    }

    /**
     * The standard name for a Mode-01 PID or Mode-09 info type, or "" if it is not one.
     *
     * FREE, AND IT SHOULD HAVE BEEN HERE FROM THE START. Mode 22 is manufacturer-specific,
     * which is the whole reason this app exists -- nobody publishes those. Mode 01 and
     * Mode 09 are the opposite: SAE J1979 and ISO 15031-5 define them, so "0105 is engine
     * coolant temperature" is a fact of a public standard rather than anyone's work, and
     * costs 4.9 KB to carry. Until this the app named nine of them, from the anchor list,
     * and a Highlander record stored twenty as bare hex.
     *
     * Returns name and unit; unit is "" where the standard defines none (a status word or
     * a support bitmap).
     */
    fun standardName(request: String): Pair<String, String> {
        val r = request.uppercase().replace(" ", "")
        if (r.length < 4) return "" to ""
        val table = when (r.take(2)) {
            "01" -> stdPids?.optJSONObject("mode01")
            "09" -> stdPids?.optJSONObject("mode09")
            else -> null
        } ?: return "" to ""
        val e = table.optJSONObject(r.substring(2, 4)) ?: return "" to ""
        return e.optString("n") to e.optString("u")
    }

    /** A DID somebody identified on a real car: what it is, and how sure they were. */
    data class Signal(val did: String, val name: String, val unit: String,
                      val header: String, val confidence: String)

    /**
     * Identifiers NAMED on a real car of this make and model.
     *
     * The README says naming is the limit this app cannot pass: it finds which identifiers
     * answer, not what they mean. That is true of a single scan and it does not have to
     * stay true of the project. One owner verifies 221700 against a dashboard, and every
     * later F10 scan can say "odometer, km" without repeating the work.
     *
     * Deliberately narrow. A name here means somebody watched a number move against
     * something real, and `confidence` says which -- "ground-truth" is the dashboard, and
     * anything weaker should read as a guess and be shown as one.
     */
    fun contributedSignals(make: String, model: String = ""): List<Signal> {
        val loc = contributed?.optJSONObject("locations") ?: return emptyList()
        val out = ArrayList<Signal>()
        for (k in loc.keys()) {
            if (!k.substringBefore('|').equals(make, ignoreCase = true)) continue
            if (model.isNotEmpty() && k.contains('|') &&
                !k.substringAfter('|').equals(model, ignoreCase = true)) continue
            val sig = loc.optJSONObject(k)?.optJSONObject("sig") ?: continue
            for (did in sig.keys()) {
                val e = sig.optJSONObject(did) ?: continue
                out.add(Signal(did, e.optString("n"), e.optString("u"),
                               e.optString("h"), e.optString("c")))
            }
        }
        return out.sortedBy { it.did }
    }

    /**
     * Every Mode-22 identifier a real car of this make and model actually answered.
     *
     * ASK WHAT WE KNOW BEFORE SWEEPING FOR IT. A blind sweep asks 256 identifiers per block
     * to find roughly 25, and runs that way even on a car this project has already mapped.
     * Confirming the measured list instead is 572 requests on a BMW F10 against 5,888 for
     * the sweep and 3,584 for the recon that precedes it -- 1.7 minutes against 24, at the
     * rate real runs achieve. The operator has a drive-log plan before the sweep starts.
     *
     * ORDER, NEVER BOUNDS. Nothing here entitles the sweep to skip anything. A record says
     * what to ask first; it never says what to leave out, because absence from a record is
     * weak evidence and this project has already been caught by it -- a BMW F10 answered on
     * three blocks the community list did not contain. The sweep still runs in full.
     *
     * Shipped packed: suffixes only, concatenated, grouped by header, the 22 implied. All
     * six current records are 15.5 KB. See tools/merge_vehicles.py.
     */
    fun contributedRequests(make: String, model: String = ""): List<Pair<String, String>> {
        // MATCHED WITHOUT REGARD TO CASE, like every other model lookup here.
        //
        // supportedForModel was made case-insensitive this morning because OBDb writes
        // "IONIQ 5" where a person writes "Ioniq 5". These three were left exact, and the
        // first BMW run on a real car found the cost: the OBDb model tier matched and ours
        // did not, so phase 0 offered 30 requests instead of 602 and sent 11. The confirm
        // pass -- the whole of phase 1 -- silently did nothing, and the session spent its
        // ten minutes on recon with two blocks swept at the end of it.
        //
        // The model name reaching these functions comes from vPIC, from a contributed
        // record, or from an operator typing it. Expecting three sources to agree on case
        // is a bet this project has now lost twice.
        val loc = contributed?.optJSONObject("locations") ?: return emptyList()
        val out = LinkedHashSet<Pair<String, String>>()
        for (k in loc.keys()) {
            if (!k.substringBefore('|').equals(make, ignoreCase = true)) continue
            if (model.isNotEmpty() && k.contains('|') &&
                !k.substringAfter('|').equals(model, ignoreCase = true)) continue
            val ids = loc.optJSONObject(k)?.optJSONObject("ids") ?: continue
            for (hdr in ids.keys()) {
                val packed = ids.optString(hdr)
                var i = 0
                while (i + 4 <= packed.length) {
                    out.add(hdr.uppercase() to "22" + packed.substring(i, i + 4))
                    i += 4
                }
            }
        }
        return out.toList()
    }

    /**
     * Locations measured on a real car of this make (and model, when known).
     *
     * These outrank the community lists because they were observed rather than documented.
     * The F10 is the proof: 2258xx carries 227 identifiers and 224Axx the oil row, and
     * neither appears in OBDb's BMW list at all.
     */
    fun contributedHints(make: String, model: String = ""): List<Hint> {
        val loc = contributed?.optJSONObject("locations") ?: return emptyList()
        val out = ArrayList<Hint>()
        for (k in loc.keys()) {
            val km = k.substringBefore('|')
            if (km != make) continue
            // An exact model wins; with no model, every record for the make contributes.
            if (model.isNotEmpty() && k.contains('|') &&
                !k.substringAfter('|').equals(model, ignoreCase = true)) continue
            val e = loc.optJSONObject(k) ?: continue
            val hdrs = e.optJSONArray("hdr") ?: continue
            val blks = e.optJSONArray("blk") ?: continue
            for (i in 0 until hdrs.length()) for (j in 0 until blks.length()) {
                // Asset stores whole block names ("2244"); a Hint carries the byte after
                // 0x2200, which is what blockPrefixes() reads back.
                val b = blks.optString(j).takeLast(2)
                val h = Hint(hdrs.optString(i), "22", b, true)
                if (h !in out) out.add(h)
            }
        }
        return out
    }

    /**
     * Every documented (header, service, block) for a make.
     *
     * These REORDER a scan, they never restrict it — and the BMW data is the proof. OBDb
     * lists blocks 40,41,43,44,45,4C,57... for BMW, but an on-car sweep of an F10 found its
     * 462 DIDs in 42,43,44,45,4A,58. Three of the six — including 2258xx with 227 DIDs and
     * the oil-pressure row — are absent from the community list entirely. Probing only what
     * is written down would have lost 358 of 462 DIDs, and would reproduce the failure that
     * hid oil temperature for a month: 2244xx was not in the preset, so a DID the project's
     * own documentation already named was never queried.
     *
     * Hinted locations go first because they pay off in the first minute. The blind sweep
     * still follows, and it is what finds the rest.
     */
    fun hintsFor(make: String, also: List<String> = emptyList(),
                 model: String = ""): List<Hint> {
        // On-car observations lead; the community lists follow and still contribute
        // everything they know that was not seen.
        val out = ArrayList<Hint>(contributedHints(make, model))
        // Primary make first so its locations keep their head start; siblings only extend
        // the tail. Deduped because plants that share a brand share documented rows.
        for (m in listOf(make) + also) {
            val arr = hints?.optJSONArray(m) ?: continue
            for (i in 0 until arr.length()) {
                val r = arr.optJSONArray(i) ?: continue
                if (r.length() >= 4) {
                    val h = Hint(r.optString(0), r.optString(1), r.optString(2), r.optInt(3) == 1)
                    if (h !in out) out.add(h)
                }
            }
        }
        return out
    }

    /**
     * Mode-22 block prefixes this make is known to use, e.g. 0x2244.
     *
     * Powertrain-pathed rows only by default. The filter is OBDb's own `path` on each
     * signal (Engine/Fuel/Transmission/...), which is better evidence than the address-range
     * rule it replaces: that rule excluded Toyota's engine module at 700 while admitting
     * addresses it knew nothing about.
     */
    fun blockPrefixes(make: String, powertrainOnly: Boolean = true, also: List<String> = emptyList()): List<Int> =
        hintsFor(make, also)
            .filter { it.service == "22" && it.block.length == 2 && (!powertrainOnly || it.powertrain) }
            .mapNotNull { it.block.toIntOrNull(16) }
            .distinct().map { 0x2200 or it }.sorted()

    /**
     * Headers this make answers Mode 22 on AND that this app can actually address.
     *
     * Only plain 11-bit headers, which is all `AT SH` alone selects. Two documented kinds
     * are deliberately excluded because handing them to ATSH would not merely fail, it
     * would fail QUIETLY -- the adapter accepts the command and every subsequent probe
     * returns nothing, which is indistinguishable from a car that has no data there:
     *
     *   6F1  BMW extended addressing. Needs AT CEA <target> and AT CRA as well; the header
     *        alone addresses nothing. This is most of OBDb's BMW data.
     *   DA10, D016, ... 29-bit targets, written in short form. Need AT SP7 and AT CP.
     *
     * They are still surfaced by unaddressable(), so the screen can say what is known but
     * out of reach rather than pretending it does not exist.
     */
    /**
     * The Volkswagen Auto Group marques -- VW, Audi, Porsche, Skoda, SEAT, Cupra, Bentley,
     * Lamborghini, Bugatti -- which share platforms and electrical architecture, and so
     * plausibly share the module layout the exclusion below is about.
     *
     * Only Audi is attested. The rest are extension by shared architecture, which is an
     * inference -- recorded as one, and the cheap direction to be wrong in.
     */
    private val VAG = setOf(
        "AUDI", "VOLKSWAGEN", "PORSCHE", "SEAT", "SKODA", "BENTLEY", "LAMBORGHINI",
        "BUGATTI", "CUPRA",
    )

    /**
     * Headers not to probe on this make, whatever the defaults and the hint table say.
     *
     * From obd-gauge-cluster's Audi preset, which excludes the range in-source: Audi
     * powertrain is engine 7E0 and TCM 7E1, and "NEVER 7E2-7E7 -- 7E4 is a driver-assist
     * module and reading it trips pre-sense warnings."
     *
     * EVERYTHING THIS APP SENDS IS READ-ONLY, AND THAT IS NOT THE SAME CLAIM as no side
     * effects. The finding is about a warning raised by a READ, on a module whose job is to
     * react to its inputs. A dash light on a stranger's car is not a cost this project gets
     * to weigh against a few more identifiers.
     *
     * IT IS NOT 7E4 THAT REACHES A VAG CAR. 7E4 is hinted for fourteen makes -- all GM,
     * Ford, Hyundai/Kia, JLR, Mazda, MG, Tata -- and no VAG make hints it, so it was never
     * sent to one. What reaches a VAG car in that range is 7E2, from HEADERS_11BIT, which is
     * make-independent. Excluding only the header the note names would protect nothing.
     *
     * 7E5 IS DELIBERATELY KEPT, against the letter of the note. Checked against OBDb's own
     * signalsets, which is where our hints come from: Audi, Volkswagen, Porsche and Skoda
     * each document 575 signals at 7E5, and every one is high-voltage battery -- 537 HVBAT_*
     * and 37 BMS_* covering cell voltages, module temperatures, SOC, SOH and charge limits.
     * 7E2, 7E3, 7E4, 7E6 and 7E7 document NOTHING on any of them.
     *
     * So the range splits cleanly. The five empty headers cost nothing to exclude and one of
     * them is the attested hazard. 7E5 is a battery module with 575 community-documented
     * fields, not the driver-assist module the warning is about, and blanket-excluding it
     * would blind this app to the entire battery dataset of an e-tron, an ID. or a Taycan --
     * exactly the data a discovery tool exists to find. A range exclusion written to keep a
     * gauge cluster off a radar should not cost an EV its battery.
     *
     * (The four marques being byte-identical means OBDb propagated one signalset across the
     * group, so this is one characterisation applied group-wide, not four confirmations.)
     *
     * CONFIDENCE: another project's field note for the exclusion, community signalsets for
     * the carve-out -- neither is our measurement, and nobody here has a VAG vehicle. Applied
     * anyway because the errors are not symmetric: being wrong about the five empty headers
     * costs nothing at all, and being right and not acting costs somebody a warning light.
     */
    fun excludedHeaders(make: String, also: List<String> = emptyList()): Set<String> {
        val names = (listOf(make) + also).map { it.trim().uppercase() }
        if (names.none { it in VAG }) return emptySet()
        // 7E5 omitted on purpose -- see above. It is the HV battery, not driver assist.
        return setOf("7E2", "7E3", "7E4", "7E6", "7E7")
    }

    fun headers(make: String, powertrainOnly: Boolean = true, also: List<String> = emptyList()): List<String> =
        hintsFor(make, also)
            .filter {
                it.service == "22" && (!powertrainOnly || it.powertrain) &&
                    it.header.length == 3 && it.header != "6F1" &&
                    it.header.all { c -> c in "0123456789ABCDEFabcdef" }
            }
            .map { it.header.uppercase() }.distinct().sorted()

    /**
     * Documented 29-bit targets, as full six-character headers.
     *
     * `headers()` keeps only three-character names, so every 29-bit hint OBDb carries was
     * being dropped silently -- and the 29-bit fallback used a fixed list that does not
     * include them. OBDb puts 45 of the Silverado 1500's 52 commands on DA11, which is
     * absent from HEADERS_29BIT, so the header holding most of that truck's enhanced data
     * had no way of being probed.
     *
     * OBDb writes the target as "DA11"; the bus address is DA11F1, tester F1 appended.
     */
    fun headers29(make: String, powertrainOnly: Boolean = true, also: List<String> = emptyList()): List<String> =
        hintsFor(make, also)
            .filter {
                it.service == "22" && (!powertrainOnly || it.powertrain) &&
                    it.header.length == 4 && it.header.uppercase().startsWith("DA") &&
                    it.header.all { c -> c in "0123456789ABCDEFabcdef" }
            }
            .map { it.header.uppercase() + "F1" }.distinct().sorted()

    /** Documented Mode-22 headers this app cannot address, with the reason. */
    fun unaddressable(make: String, also: List<String> = emptyList()): List<Pair<String, String>> =
        hintsFor(make, also).filter { it.service == "22" && it.header.isNotEmpty() }
            .map { it.header }.distinct().sorted()
            .mapNotNull { h ->
                when {
                    // 6F1 is the tester address in ISO-TP EXTENDED addressing, where the
                    // target ECU is selected by a separate byte (AT CEA) rather than by the
                    // header. BMW uses it heavily, which is why it was labelled that way --
                    // but a 2006 Toyota showed the label reading "BMW extended addressing"
                    // on a Toyota, which is simply wrong. The scheme is not BMW's property.
                    // 6F1 IS reachable now -- Discover.BMW_TARGETS expands it via AT CEA and
                    // AT CRA. Only the targets documented as powertrain are tried, so the
                    // rest of that address space stays unvisited and is still worth naming.
                    h == "6F1" -> h to "extended addressing — targets ${Discover.BMW_TARGETS.joinToString("/")} only"
                    h.length > 3 -> h to "29-bit target (needs AT SP7/CP)"
                    else -> null
                }
            }

    /**
     * (header, block-prefix) pairs this make is documented to answer on.
     *
     * Recon probes seven offsets per block, which finds a block only if one of its DIDs
     * happens to sit on a probed offset. Measured on a Ford Ranger, 2026-08-26: blocks
     * 221Exx, 22F4xx and 2228xx were reported absent, while OBDb documents transmission oil
     * temperature at 221E1C, fuel level at 22F42F and tyre pressures at 222813-16 -- offsets
     * 0x12 to 0x2F, none of them probed. The block was not empty; the sampling missed it.
     *
     * These pairs are therefore swept IN FULL rather than sampled, whenever their header is
     * alive. It is a targeted cost -- 26 pairs on that Ranger, about nine minutes -- and it
     * applies only where the community has already recorded that data exists.
     */
    fun hintedPairs(make: String, powertrainOnly: Boolean = false, also: List<String> = emptyList()): List<Pair<String, Int>> =
        hintsFor(make, also)
            .filter {
                it.service == "22" && it.block.length == 2 &&
                    it.header.length == 3 && it.header != "6F1" &&
                    it.header.all { c -> c in "0123456789ABCDEFabcdef" } &&
                    (!powertrainOnly || it.powertrain)
            }
            .mapNotNull { hn -> hn.block.toIntOrNull(16)?.let { hn.header.uppercase() to (0x2200 or it) } }
            .distinct()

    /**
     * Exact (header, request) pairs this make is KNOWN to answer, from OBDb's per-model-year
     * command_support censuses -- real supported-command captures, not inference.
     *
     * This is what block hints should have been. A block hint says "something lives in
     * 221Exx" and costs 256 probes to act on; this says the answer is 221E1C and costs one.
     * Measured on a Ford Ranger: the six documented DIDs the offset sampling missed cost 181
     * probes to ask for directly, against 6656 to find them by sweeping the hinted blocks --
     * fifteen seconds instead of nine minutes, and better coverage.
     *
     * Mode 21 entries are filtered out: the whitelist does not permit sending them.
     */
    fun supportedFor(make: String): List<Pair<String, String>> {
        val arr = supported?.optJSONArray(make) ?: return emptyList()
        val out = ArrayList<Pair<String, String>>(arr.length())
        for (i in 0 until arr.length()) {
            val row = arr.optString(i)
            val c = row.indexOf(':')
            if (c <= 0) continue
            val hdr = row.substring(0, c).uppercase()
            val req = row.substring(c + 1).uppercase()
            // Plain 11-bit headers only, and Mode 22 only -- same limits as headers().
            // 29-bit targets are written as four characters ("DA11"); the bus address is
            // DA11F1. Filtering to three dropped every one, so on a 29-bit vehicle phase 0
            // matched nothing against liveHeaders: a Silverado offered 409 known requests
            // and sent 20, all of which were the identification DIDs.
            val h = when {
                hdr.length == 3 && hdr != "6F1" -> hdr
                hdr.length == 4 && hdr.startsWith("DA") -> hdr + "F1"
                else -> continue
            }
            if (!h.all { it in "0123456789ABCDEF" }) continue
            if (!req.startsWith("22") || req.length < 6) continue
            out.add(h to req)
        }
        return out.distinct()
    }

    /**
     * True if this make is known to use Mode 21 for enhanced data.
     *
     * Said "which we cannot send" until the Mode-21 sweep landed. It is sent on KWP2000,
     * and on ISO 9141-2 behind the opt-in.
     */
    fun usesMode21(make: String, also: List<String> = emptyList()): Boolean =
        hintsFor(make, also).any { it.service == "21" }
}
